# Generated by Django 3.2.3 on 2021-10-18 23:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('weight', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
