# Generated by Django 3.2.3 on 2021-10-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20211020_1818'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name_plural': 'Ordered Item'},
        ),
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'verbose_name_plural': 'Shipping Address'},
        ),
        migrations.AlterField(
            model_name='product',
            name='featured_image',
            field=models.ImageField(upload_to='product_images'),
        ),
    ]
