# Generated by Django 3.2.3 on 2021-11-04 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_zipcode_shippingaddress_nearlestlandmark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='nearlestlandmark',
            new_name='nearestlandmark',
        ),
    ]
