# Generated by Django 3.2.3 on 2021-11-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_rename_nearlestlandmark_shippingaddress_nearestlandmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='barangay',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
