# Generated by Django 3.2.3 on 2021-11-05 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_shippingaddress_barangay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
